"""LiteLLM config sample generator — produces verified YAML routing config."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Optional

import yaml

from free_ai_model_router.models import (
    FreeStatus,
    ModelRating,
    ProviderEndpoint,
    QualityBand,
    RouterOutput,
    RoutedEndpoint,
    ScoringConfig,
    ScoringMode,
)

logger = logging.getLogger(__name__)


def _litellm_model_string(endpoint: ProviderEndpoint) -> str:
    """Get LiteLLM-compatible model string for an endpoint."""
    return endpoint.litellm_model or f"{endpoint.provider_id}/{endpoint.provider_model_id}"


def build_fallback_chain(
    endpoints: list[tuple[ProviderEndpoint, ModelRating]],
    config: ScoringConfig,
) -> list[RoutedEndpoint]:
    """Build a sorted, diverse-provider fallback chain.

    Rules:
    - Primary = highest quality with acceptable reliability
    - Subsequent models should be from different providers when possible
    - Models sharing a daily quota are not independent fallbacks
    - Temporary-free models must not be the sole route
    """
    if not endpoints:
        return []

    # Sort by final_router_score descending
    scored = sorted(
        endpoints,
        key=lambda x: x[1].normalized_scores.final_router_score or 0,
        reverse=True,
    )

    routed: list[RoutedEndpoint] = []
    used_providers: set[str] = set()
    has_permanent_free = False
    rank = 0

    for endpoint, rating in scored:
        final_score = rating.normalized_scores.final_router_score or 0
        if final_score < config.quality_threshold_percent:
            continue

        # Skip if same provider already used and diversity preferred
        if config.routing.prefer_provider_diversity and endpoint.provider_id in used_providers:
            # Check if shared quota prevents independence
            if config.routing.disallow_shared_quota_as_independent_fallback:
                # Check if any existing routed endpoint shares quota with this one
                if endpoint.limits.shared_quota_group:
                    continue

        # Track if we have a permanent free model
        if endpoint.free_status in (FreeStatus.VERIFIED_FREE, FreeStatus.DOCUMENTED_FREE):
            has_permanent_free = True

        rank += 1
        used_providers.add(endpoint.provider_id)
        routed.append(RoutedEndpoint(
            endpoint_id=endpoint.endpoint_id,
            provider_id=endpoint.provider_id,
            provider_name=endpoint.provider_id,
            canonical_model_id=endpoint.canonical_model_id,
            model_name=endpoint.provider_model_id,
            final_score=final_score,
            quality_band=rating.quality_band,
            free_status=endpoint.free_status,
            rank=rank,
            is_primary=(rank == 1),
        ))

    # Validate: if only temporary free models, log warning
    if not has_permanent_free and routed:
        logger.warning("Fallback chain has no permanent free model — all models are temporary/account-specific free")

    return routed


def generate_litellm_config(
    router_output: RouterOutput,
    endpoints_map: dict[str, ProviderEndpoint],
) -> str:
    """Generate a LiteLLM config YAML sample.

    Structure follows LiteLLM proxy config format with model_list and router_settings.
    No real API keys are included — uses os.environ/VARIABLE_NAME.
    """
    config_lines: list[str] = []
    config_lines.append("# LiteLLM Config Sample — Auto-generated by Free AI Model Router")
    config_lines.append(f"# Generated at: {router_output.generated_at.isoformat()}")
    config_lines.append(f"# Scoring mode: {router_output.scoring_mode.value}")
    config_lines.append(f"# Reference: {router_output.reference_scored_at or 'N/A'}")
    config_lines.append("#")
    config_lines.append("# WARNING: This is a sample config. Review before using in production.")
    config_lines.append("# Add your actual API keys as environment variables.")
    config_lines.append("")

    # Model list
    config_lines.append("model_list:")

    for routed_ep in router_output.endpoints:
        ep = endpoints_map.get(routed_ep.endpoint_id)
        if not ep:
            continue

        model_name = f"coding-{'primary' if routed_ep.is_primary else f'fallback-{routed_ep.rank - 1}'}"

        # Comment block
        config_lines.append(f"  # {routed_ep.provider_name} :: {routed_ep.model_name}")
        config_lines.append(f"  #   Score: {routed_ep.final_score:.1f}% | Band: {routed_ep.quality_band.value}")
        config_lines.append(f"  #   Free status: {routed_ep.free_status.value}")
        config_lines.append(f"  #   Verified: {'yes' if ep.runtime_check.checked else 'no'}")
        config_lines.append(f"  #   Rank: {routed_ep.rank}")

        if routed_ep.free_status in (FreeStatus.ACCOUNT_SPECIFIC_FREE, FreeStatus.TEMPORARY_FREE):
            config_lines.append(f"  #   NOTE: {routed_ep.free_status.value} — verify before relying on this route")

        config_lines.append(f"  - model_name: {model_name}")
        config_lines.append("    litellm_params:")
        config_lines.append(f"      model: {_litellm_model_string(ep)}")
        if ep.api_base:
            config_lines.append(f"      api_base: {ep.api_base}")

        # API key env var
        env_var = f"{ep.provider_id.upper()}_API_KEY"
        config_lines.append(f"      api_key: os.environ/{env_var}")
        config_lines.append("      timeout: 180")
        config_lines.append("")

    # Router settings with fallbacks
    config_lines.append("router_settings:")
    config_lines.append("  fallbacks:")

    # Build fallback model names
    fallback_names = []
    for i, routed_ep in enumerate(router_output.endpoints):
        if i == 0:
            fallback_names.append(f"coding-{'primary' if routed_ep.is_primary else f'fallback-{routed_ep.rank - 1}'}")
        else:
            fallback_names.append(f"coding-fallback-{i}")

    if fallback_names:
        config_lines.append(f"    - coding-auto:")
        for name in fallback_names:
            config_lines.append(f"        - {name}")

    config_lines.append("    ")  # blank entry to close list
    config_lines.append("  num_retries: 0")
    config_lines.append("  cooldown_time: 300")
    config_lines.append("  allowed_fails: 1")
    config_lines.append("  enable_pre_call_checks: true")
    config_lines.append("")

    config_lines.append("litellm_settings:")
    config_lines.append("  drop_params: true")
    config_lines.append("")

    return "\n".join(config_lines)


def generate_litellm_config_file(
    router_output: RouterOutput,
    endpoints: list[ProviderEndpoint],
    output_path: str,
) -> None:
    """Generate and write LiteLLM config to file."""
    endpoints_map = {e.endpoint_id: e for e in endpoints}
    yaml_content = generate_litellm_config(router_output, endpoints_map)

    import pathlib
    path = pathlib.Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml_content, encoding="utf-8")
    logger.info("Generated LiteLLM config at %s", output_path)
