"""LiteLLM config sample generator — produces verified YAML routing config."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Optional

from free_ai_model_router.models import (
    FreeStatus,
    ProviderEndpoint,
    RouterOutput,
)

logger = logging.getLogger(__name__)


def _litellm_model_string(endpoint: ProviderEndpoint) -> str:
    """Get LiteLLM-compatible model string for an endpoint."""
    return endpoint.litellm_model or f"{endpoint.provider_id}/{endpoint.provider_model_id}"


def generate_litellm_config(
    router_output: RouterOutput,
    endpoints_map: dict[str, ProviderEndpoint],
) -> str:
    """Generate a LiteLLM config YAML sample.

    Structure follows LiteLLM proxy config format with model_list and router_settings.
    No real API keys are included — uses os.environ/VARIABLE_NAME.
    """
    config_lines: list[str] = []
    config_lines.append("# LiteLLM Config Sample — Auto-generated by Free AI Model Router")
    config_lines.append(f"# Generated at: {router_output.generated_at.isoformat()}")
    config_lines.append("#")
    config_lines.append("# WARNING: This is a sample config. Review before using in production.")
    config_lines.append("# Add your actual API keys as environment variables.")
    config_lines.append("")

    # Model list
    config_lines.append("model_list:")

    for i, routed_ep in enumerate(router_output.endpoints):
        ep = endpoints_map.get(routed_ep.endpoint_id)
        if not ep:
            continue

        model_name = f"coding-auto-{i + 1}"

        # Comment block with tools and modality info
        tools_str = "yes" if routed_ep.tool_calling else "no"
        modality_str = ", ".join(routed_ep.modalities) if routed_ep.modalities else "text"
        config_lines.append(f"  # {routed_ep.provider_name} :: {routed_ep.model_name}")
        config_lines.append(f"  #   Tools: {tools_str}")
        config_lines.append(f"  #   Modality: {modality_str}")
        config_lines.append(f"  #   Free status: {routed_ep.free_status.value}")

        if routed_ep.free_status in (FreeStatus.ACCOUNT_SPECIFIC_FREE, FreeStatus.TEMPORARY_FREE):
            config_lines.append(f"  #   NOTE: {routed_ep.free_status.value} — verify before relying on this route")

        config_lines.append(f"  - model_name: {model_name}")
        config_lines.append("    litellm_params:")
        config_lines.append(f"      model: {_litellm_model_string(ep)}")
        if ep.api_base:
            config_lines.append(f"      api_base: {ep.api_base}")

        # API key env var
        env_var = f"{ep.provider_id.upper()}_API_KEY"
        config_lines.append(f"      api_key: os.environ/{env_var}")
        config_lines.append("      timeout: 180")
        config_lines.append("")

    # Router settings with fallbacks
    config_lines.append("router_settings:")
    config_lines.append("  fallbacks:")

    # Build fallback model names
    fallback_names = [f"coding-auto-{i + 1}" for i in range(len(router_output.endpoints))]

    if fallback_names:
        config_lines.append(f"    - coding-auto:")
        for name in fallback_names:
            config_lines.append(f"        - {name}")

    config_lines.append("    ")  # blank entry to close list
    config_lines.append("  num_retries: 0")
    config_lines.append("  cooldown_time: 300")
    config_lines.append("  allowed_fails: 1")
    config_lines.append("  enable_pre_call_checks: true")
    config_lines.append("")

    config_lines.append("litellm_settings:")
    config_lines.append("  drop_params: true")
    config_lines.append("")

    return "\n".join(config_lines)


def generate_litellm_config_file(
    router_output: RouterOutput,
    endpoints: list[ProviderEndpoint],
    output_path: str,
) -> None:
    """Generate and write LiteLLM config to file."""
    endpoints_map = {e.endpoint_id: e for e in endpoints}
    yaml_content = generate_litellm_config(router_output, endpoints_map)

    import pathlib
    path = pathlib.Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml_content, encoding="utf-8")
    logger.info("Generated LiteLLM config at %s", output_path)
